# Tela embutida (principal)
monitor = eDP-1,1920x1080@165,0x420,1.5

# HKM 25" (secundário, em retrato à direita)
monitor = HDMI-A-2,1920x1080@120,auto,1,transform,1

# Terminal (Ghostty)
bind = SUPER, T, exec, ghostty

# Launcher (Wofi)
bind = SUPER, D, exec, wofi --show drun

# Kill janela
bind = SUPER, Q, killactive,

# Screenshot
bind = SUPER SHIFT, S, exec, ~/.config/hypr/scripts/screenshot-monitor.sh

# Fullscree
bind = SUPER, F, fullscreen,

# Use SUPER + W/A/S/D para mudar a janela ativa sem alterar o layout.
bind = SUPER, UP, movefocus, u
bind = SUPER,DOWN, movefocus, d
bind = SUPER, LEFT, movefocus, l
bind = SUPER, RIGHT, movefocus, r

# Use SUPER + SHIFT + W/A/S/D para fazer a janela ativa trocar de lugar com a vizinha.
bind = SUPER + SHIFT, UP, swapwindow, u
bind = SUPER SHIFT, DOWN, swapwindow, d
bind = SUPER SHIFT, LEFT, swapwindow, l
bind = SUPER SHIFT, RIGHT, swapwindow, r

# Tela de bloqueio
bind = SUPER, L, exec, hyprlock

# Decorations
source = ~/.config/hypr/decorations.conf

# Waybar
exec-once = waybar

# hyprpaper
exec-once = hyprpaper

# ABNT2
input {
    kb_layout = br         # Layout brasileiro
    kb_variant = abnt2     # Variante ABNT2 (com Ç)
}

# Ponteiro correto
input {
  # Tenta aplicar rotação ao cursor também
  follow_mouse = yes
  force_no_accel = true
  touchpad {
    natural_scroll = true
  }
}

# Arrastar janelas
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# WORKSPACES
# Todos os workspaces no monitor principal (laptop)
workspace = 1, monitor:eDP-1, default:true, persistent:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true  
workspace = 4, monitor:eDP-1, persistent:true
workspace = 5, monitor:HDMI-A-2, 

# Keybinds garantindo foco no monitor principal
bind = ALT, 1, focusmonitor, eDP-1
bind = ALT, 1, workspace, 1
bind = ALT, 2, focusmonitor, eDP-1
bind = ALT, 2, workspace, 2
bind = ALT, 3, focusmonitor, eDP-1
bind = ALT, 3, workspace, 3
bind = ALT, 4, focusmonitor, eDP-1
bind = ALT, 4, workspace, 4
bind = ALT, 5, focusmonitor, HDMI-A-2
bind = ALT, 5, workspace, 5, HDMI-A-2

# Mover janelas sempre para o monitor principal
bind = ALT, F1, movetoworkspace, 1
bind = ALT, F1, focusmonitor, eDP-1
bind = ALT, F2, movetoworkspace, 2
bind = ALT, F2, focusmonitor, eDP-1
bind = ALT, F3, movetoworkspace, 3
bind = ALT, F3, focusmonitor, eDP-1
bind = ALT, F4, movetoworkspace, 4
bind = ALT, F5, movetoworkspace, 5

# VS Code
windowrule = opacity 0.7, class:^(Code)$
