# ~/.config/hypr/hyprlock.conf

# Configurações de fundo
background {
    # O caminho para a sua imagem de fundo. Use um caminho absoluto.
    path = ~/Imagens/wpp/wpp.png 
    # Ativa o desfoque. Requer poder de processamento, mas o efeito é excelente.
    blur_size = 8
    blur_passes = 2
}

# Configurações gerais
general {
    # Desativa a barra de "carregamento" que aparece por padrão.
    disable_loading_bar = true
    # Esconde o cursor do mouse.
    hide_cursor = true
}

# O campo de entrada de senha
input-field {
    # Tamanho da caixa de entrada (largura x altura)
    size = 250, 50
    # Posição na tela. Use `0, 0` para o centro.
    position = 0, -80 
    # Alinhamento horizontal (left, center, right)
    halign = center
    # Alinhamento vertical (top, center, bottom)
    valign = center

    # Cores (formato RGBA: cor e transparência)
    inner_color = rgb(000, 0.5)
    outer_color = rgb(32, 32, 32, 0.8)
    outline_thickness = 2
    
    # Efeito de fade ao aparecer
    fade_on_empty = true
    # O texto que aparece dentro da caixa
    placeholder_text = <i>Senha...</i>
}

# O relógio
label {
    monitor =
    text = cmd[date +%H:%M] # Usa um comando de shell para pegar a hora
    color = rgba(255, 255, 255, 0.9)
    font_size = 90
    font_family = "Adwaita Mono"

    position = 0, 80
    halign = center
    valign = center
}

# Um texto de boas-vindas
label {
    monitor =
    text = Olá, $USER
    color = rgba(200, 200, 200, 0.8)
    font_size = 25
    font_family = "Adwaita Mono"
    position = 0, -150
    halign = center
    valign = center
}
