preload = /home/caio/Imagens/wpp/wpp.png
wallpaper = eDP-1,/home/caio/Imagens/wpp/wpp.png  # Monitor principal (ajuste o nome se necessário)
# Se tiver segundo monitor:
wallpaper = HDMI-A-2,/home/caio/Imagens/wpp/wpp.png


