# Tela embutida (principal)
monitor = eDP-1,1920x1080@165,0x0,1

# HKM 25" (secundário, em retrato à direita)
monitor = HDMI-A-2,1920x1080@120, 1920x0, 1, transform, 1

# Terminal (Ghostty)
bind = SUPER, T, exec, ghostty

# Launcher (Wofi)
bind = SUPER, D, exec, wofi --show drun

# Kill janela
bind = SUPER, Q, killactive,

# Screenshot
bind = SUPER SHIFT, S, exec, ~/.config/hypr/scripts/screenshot-monitor.sh

# Fullscree
bind = SUPER, F, fullscreen,

# Mover entre janelas
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Decorations
source = ~/.config/hypr/decorations.conf

# Waybar
exec-once = waybar

# hyprpaper
exec-once = hyprpaper

# ABNT2
input {
    kb_layout = br         # Layout brasileiro
    kb_variant = abnt2     # Variante ABNT2 (com Ç)
}

# Ponteiro correto
input {
  # Tenta aplicar rotação ao cursor também
  follow_mouse = yes
  force_no_accel = true
  touchpad {
    natural_scroll = true
  }
}

# Arrastar janelas
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# WORKSPACES
# Todos os workspaces no monitor principal (laptop)
workspace = 1, monitor:eDP-1, default:true, persistent:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true  
workspace = 4, monitor:eDP-1, persistent:true

# Keybinds garantindo foco no monitor principal
bind = ALT, 1, focusmonitor, eDP-1
bind = ALT, 1, workspace, 1
bind = ALT, 2, focusmonitor, eDP-1
bind = ALT, 2, workspace, 2
bind = ALT, 3, focusmonitor, eDP-1
bind = ALT, 3, workspace, 3
bind = ALT, 4, focusmonitor, eDP-1
bind = ALT, 4, workspace, 4

# Mover janelas sempre para o monitor principal
bind = ALT, F1, movetoworkspace, 1
bind = ALT, F1, focusmonitor, eDP-1
bind = ALT, F2, movetoworkspace, 2
bind = ALT, F2, focusmonitor, eDP-1
bind = ALT, F3, movetoworkspace, 3
bind = ALT, F3, focusmonitor, eDP-1
bind = ALT, F4, movetoworkspace, 4

# Mover janelas entre monitores
bind = ALT SHIFT, 1, movewindow, mon:DP-1
bind = ALT SHIFT, 2, movewindow, mon:HDMI-A-1
